backend:
  name: git-gateway
  branch: master
  repo: Lokolin/gatsby-bee-netlify

media_folder: 'static/img'
public_folder: '/img'

collections:
  - name: blog
    label: 'Post'
    folder: 'content/blog/development'
    # media_folder: blog
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}.md'
    create: true
    fields:
      - { name: 'path', label: 'Path' }
      - { name: 'date', label: 'Date', widget: 'datetime' }
      - { name: 'title', label: 'Title' }
      - { name: 'body', label: 'Body', widget: 'markdown' }
      - { name: 'category', label: 'category' }
      - {
          label: 'Body',
          name: 'body',
          widget: 'slides',
          separator: "\n\n<!--s-->\n\n",
        }
